// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace volkrenderer {
	
	
	// Should subclass MonoMac.AppKit.NSWindow
	[MonoMac.Foundation.Register("MainWindow")]
	public partial class MainWindow {
	}
	
	// Should subclass MonoMac.AppKit.NSWindowController
	[MonoMac.Foundation.Register("MainWindowController")]
	public partial class MainWindowController {
		
		private global::MonoMac.AppKit.NSTextField __mt_myOutlet1;
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Export("render:")]
		partial void render (MonoMac.AppKit.NSButton sender);

		[MonoMac.Foundation.Connect("myOutlet1")]
		private global::MonoMac.AppKit.NSTextField myOutlet1 {
			get {
				this.__mt_myOutlet1 = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("myOutlet1")));
				return this.__mt_myOutlet1;
			}
			set {
				this.__mt_myOutlet1 = value;
				this.SetNativeField("myOutlet1", value);
			}
		}
	}
}
